spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: 1234
      connect-timeout: 1000

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/ssgpoint
        read-only: false
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/ssgpoint
        read-only: true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.workjo.pointapp: DEBUG

JWT:
  secret-key: workjojwttopsecretsecreteworkworkworkjohellohello
  expiration-time: 14400000
  header: Authorization
  prefix: Bearer