spring:
  application:
    name: SSGPOINT_APP
  profiles:
    default: local

server:
  port: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

external-api:
  naver-sms:
    service-id: ${NCP_SERVICE_ID}
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    from: ${NCP_SENDER_PHONE}

feign:
  client:
    config:
      default:
        loggerLevel: full