spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      port: 6379
      host: redis-container
      password: ${REDIS_PASSWORD}
      connect-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

JWT:
  secret-key: ${JWT_SECRET}
  expiration-time: 14400000
  header: Authorization
  prefix: Bearer