server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      port: 6379
      host: redis-container
      password: ${REDIS_PASSWORD}
      connect-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://master-db/ssgpoint?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        read-only: false
        username: ${MASTER_DB_USERNAME}
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://slave-db/ssgpoint?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        read-only: true
        username: ${SLAVE_DB_USERNAME}
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

JWT:
  secret-key: ${JWT_SECRET}
  expiration-time: 14400000
  header: Authorization
  prefix: Bearer