spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/ssgpoint
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.workjo.pointapp: DEBUG